/** This function takes in the results generated by the growthAccountingAndLTVQuery in this repository, 
as well as the id of a <div> element (of the format "#myID") you want to populate w/ the chart and renders one that mirrors 
the chart found here (https://cdn-images-1.medium.com/max/800/1*IzDnTzllwIrHixOqkR5tGA.png), but for your data **/


/** Don't forget to include the highcharts source: <script src="http://code.highcharts.com/highcharts.js"></script> **/

 function generateRetentionChart(results, desiredContainer) {
        var allSeries = [ //each object w/in this array is a data series
          {name: "04 Week LTV",  type: 'line', data: [], zIndex: 2, color: '#1DAFC9'},
          {name: "08 Week LTV",  type: 'line', data: [], zIndex: 3, color: '#577A2D'},
          {name: "12 Week LTV",  type: 'line', data: [], zIndex: 4, color: '#6F99CC'},
          {name: "16 Week LTV",  type: 'line', data: [], zIndex: 5, color: '#59C0D3'},
          {name: "20 Week LTV",  type: 'line', data: [], zIndex: 6, color: '#72A43C'},
          {name: "24 Week LTV",  type: 'line', data: [], zIndex: 7, color: '#91B2D9'},
          {name: "Cohort Size",  type: 'column', yAxis: 1, data: [], zIndex: 1, color: '#B89DC8'},
        ];
        var categories = [] //highcharts issue for charts w/ multiple types, you must specify x-axis 'categories'
        for (var cohortKey in results) {
          var cohortData = results[cohortKey]; //object for a single cohort
          var cohortStartWeek = cohortData['Cohort Week'];
          categories.push(cohortStartWeek) //handle x-axis label for specific point
          for (var seriesObjKey in allSeries) {
            var series = allSeries[seriesObjKey];
            var seriesName = series.name;
            if (seriesName != "Cohort Size") {
              series.data.push([cohortStartWeek, cohortData[seriesName]])
            } else {
              series.data.push([cohortStartWeek, cohortData["cohortSize"]])
            }
          }
        }
        //console.log(allSeries);
        /**** FINALLY MAKE THE Chart ***/
        $(desiredContainer).highcharts({ 
          chart: { zoomType: 'x'},
          title: {text: 'App Open LTV Trends'},
          xAxis: [{
            categories: categories, 
            crosshair:true,
            labels: {
                rotation: -45,
                style: {
                    fontSize: '13px',
                    fontFamily: 'Verdana, sans-serif'
                }
            }
          }],
          yAxis: [{ //primary yAxis
            title: { text: 'Cummulative App Opens'},
          }, { //secondary axis 
            title: { text: 'Cohort Size'},
            opposite: true
          }],
          tooltip: {
            shared: true,
           // pointFormat: '<span style="color:{series.color}">{series.name}</span>: <b>{point.y}</b> ({point.change}%)<br/>',
           // valueDecimals: 2
          },
          plotOptions: {
            line: {
              marker: {
                enabled: false
              }
            }, 
            series: {
              borderWidth: 0,
              //compare: 'percent'
            }
          },
          series: allSeries
        })
      }

